baseURL = 'https://muqi910.github.io/app/'
canonifyurls = true
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
publishDir = 'docs'
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true